import * as fs from "fs";
import colors from "tailwindcss/colors.js";

function isGetter(obj, prop) {
  return !!Object.getOwnPropertyDescriptor(obj, prop)['get']
}

function getTailwindColors() {
  let sass = `// This file is automatically generated, do not edit \n`;
  for (let key in colors) {
    if (colors.hasOwnProperty(key) && !isGetter(colors, key)) {
      let property = colors[key];

      if (typeof property === 'object' && property !== null) {
        for (let subKey in property) {
          if (property.hasOwnProperty(subKey)) {
            let subValue = property[subKey];
            sass += `$${key}-${subKey}: ${subValue}; \n`;
          }
        }
      } else {
        sass += `$${key}: ${property}; \n`;
      }

    }
  }
  return sass;
}

let coloursData = getTailwindColors();
fs.writeFile('scss/themes/_colors.scss', coloursData, function (err, file) {
  if (err) throw err;
})
